### ISSUE TITLE
请问怎么加载已经训练好的模型

### ISSUE THREAD

**Issue by 454812511** [HunterXuan/wx-tfjs-demo#15]
已经通过 nodejs 训练好了模型,得到两个文件, 一个是模型 json 格式, 另一个是 bin 的权值文件 , 两个一起文件都不到 100k , 在小程序中怎么使用这连个文件加载模型 ?

**Comment by HunterXuan** [comment]
先确认自己生成的 json 和权值文件是正确的，然后把他们放到某 WEB 服务器下，确保可以正常访问 json 文件和权值文件，然后用下面的示例代码加载模型
```
const MODEL_FILE_URL = 'http(s)://xxx.xxx/your/model/json/file/path'
import * as tfc from '@tensorflow/tfjs-converter'
const model = await tfc.loadGraphModel(MODEL_FILE_URL)
```
