### ISSUE TITLE
导入项目时出错module "models/body-pix/@tensorflow/tfjs-core" is not defined

### ISSUE THREAD

**Issue by 408881465** [HunterXuan/wx-tfjs-demo#21]
导入项目时出错出现如下错误：
module "models/body-pix/@tensorflow/tfjs-core" is not defined
Error: module "models/body-pix/@tensorflow/tfjs-core" is not defined

请问如何解决，谢谢！

**Comment by HunterXuan** [comment]
需要执行 `npm install`，然后使用微信开发工具的 npm 构建功能
