### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by CONAN0** [HunterXuan/wx-tfjs-demo#27]
Cannot read property 'createOffscreenCanvas' of undefined; at wx.createOffscreenCanvas
TypeError: Cannot read property 'createOffscreenCanvas' of undefined

Cannot assign to read only property 'btoa' of object '[object Window]';at "pages/posenet/index" page lifeCycleMethod onLoad function
TypeError: Cannot assign to read only property 'btoa' of object '[object Window]'

**Comment by HunterXuan** [comment]
真机调试不支持 createOffscreenCanvas，建议看下这个帖子和你的情况是否一样

https://developers.weixin.qq.com/community/develop/doc/00086e5a238ac0dcd1983092356800
