### ISSUE TITLE
Right-hand side of ‘instanceof’ is not callable

### ISSUE THREAD

**Issue by tabingithub** [HunterXuan/wx-tfjs-demo#28]
作者你好呀，我在github拉取了源代码之后，
运行了人体检测但是返回了“Right-hand side of ‘instanceof’ is not callable”这样一个错误
能麻烦给点帮助嘛？

**Comment by HunterXuan** [comment]
看一下这里的说明，理解一下 getInputSize 方法，你就知道该怎么改了
https://github.com/HunterXuan/wx-tfjs-demo/blob/master/models/body-pix/classifier.js#L63
