### ISSUE TITLE
Error: module "@tensorflow/tfjs-backend-webgl.js" is not defined

### ISSUE THREAD

**Issue by 1164513233** [HunterXuan/wx-tfjs-demo#32]
发生了这个错误。在win10上，以及安装npm，并且已经执行npm install 等操作。请问会是什么问题，谢谢！

另外，小程序能够加载云服务器中的模型。我是中学教师，想做一个平台训练数据，小程序获取训练得到的模型，在手机上做一些检测任务，供教学使用，请问能否实现？谢谢

**Comment by deepkolos** [comment]
https://github.com/deepkolos/wxmp-tensorflow

欢迎尝试，tfjs 3.6的工程解决方案，适配wasm
