### ISSUE TITLE
关于帧的同步问题，预测的时候对arraybuffer.slice一下就好了，微信小程序的frame的arraybuffer是复用的

### ISSUE THREAD

**Issue by deepkolos** [HunterXuan/wx-tfjs-demo#35]
我也整理了微信小程序运行tfjs**3.6**的工程解决方案，欢迎大佬star支持，哈哈

3.x有更好的体积裁剪方式，里面有custom tfjs的案例，配合tree shaking 可以下降52%

https://github.com/deepkolos/wxmp-tensorflow

**Comment by HunterXuan** [comment]
挺好，回头我试试
