### ISSUE TITLE
models 报 temp.slice slice is not a function 错误

### ISSUE THREAD

**Issue by hicoldcat** [HunterXuan/wx-tfjs-demo#36]
Hi，在使用demo时 , 发现 在  `https://github.com/HunterXuan/wx-tfjs-demo/blob/master/miniprogram/models/coco-ssd/classifier.js` 文件里有下面的代码，但是temp 这个对象上并没有slice这个方法，导致无法成功执行。但是我看你的小程序上是很正常的，这个是什么原因呢？感谢回复。

```
const tensor = tf.tidy(() => {
        const temp = tf.browser.fromPixels({
          data: new Uint8Array(frame.data),
          width: frame.width,
          height: frame.height,
        }, 4)

        const sliceOptions = getFrameSliceOptions(this.cameraPosition, frame.width, frame.height, this.displaySize.width, this.displaySize.height)

        return temp.slice(sliceOptions.start, sliceOptions.size).resizeBilinear([this.displaySize.height, this.displaySize.width]).asType('int32')
      })
```

![image](https://user-images.githubusercontent.com/15854702/121770881-9af5bf80-cb9e-11eb-9e65-cfd3730391a8.png)
![image](https://user-images.githubusercontent.com/15854702/121770886-a943db80-cb9e-11eb-85b3-59a14ec528a5.png)

**Comment by kingubo302** [comment]
> Hi，在使用demo时 , 发现 在 `https://github.com/HunterXuan/wx-tfjs-demo/blob/master/miniprogram/models/coco-ssd/classifier.js` 文件里有下面的代码，但是temp 这个对象上并没有slice这个方法，导致无法成功执行。但是我看你的小程序上是很正常的，这个是什么原因呢？感谢回复。
> 
> ```
> const tensor = tf.tidy(() => {
>         const temp = tf.browser.fromPixels({
>           data: new Uint8Array(frame.data),
>           width: frame.width,
>           height: frame.height,
>         }, 4)
> 
>         const sliceOptions = getFrameSliceOptions(this.cameraPosition, frame.width, frame.height, this.displaySize.width, this.displaySize.height)
> 
>         return temp.slice(sliceOptions.start, sliceOptions.size).resizeBilinear([this.displaySize.height, this.displaySize.width]).asType('int32')
>       })
> ```
> 
> ![image](https://user-images.githubusercontent.com/15854702/121770881-9af5bf80-cb9e-11eb-9e65-cfd3730391a8.png)
> ![image](https://user-images.githubusercontent.com/15854702/121770886-a943db80-cb9e-11eb-85b3-59a14ec528a5.png)

你好， 有解决吗？

**Comment by HunterXuan** [comment]
真机调试下应该是不行的

**Comment by githubhcc** [comment]
找到原因了吗
