### ISSUE TITLE
TypeError: temp.slice is not a function

### ISSUE THREAD

**Issue by Escapistarea** [HunterXuan/wx-tfjs-demo#38]
我在微信开发者工具上试了一下你的代码,模型也导入成功了,但还是出现了这个错误,我也没有在真机上调试.
![1](https://user-images.githubusercontent.com/88979122/129484524-d437c21d-70d1-4fbd-b04f-904f15acaef8.jpeg)

**Comment by HunterXuan** [comment]
直接手机预览呢？

**Comment by Escapistarea** [comment]
直接手机预览也是无法识别物品，显示网络连接错误。
这个loadgraphmodel应该是把模型封装进来成功了吧。
