### ISSUE TITLE
请问您怎么把模型压缩到只有55kb的

### ISSUE THREAD

**Issue by ynulihao** [HunterXuan/wx-tfjs-demo#4]
我使用更小的MobileNetV2也有接近20M，小程序加载速度很慢。求教怎么压缩模型。

**Comment by HunterXuan** [comment]
我的模型也不只是 55kb，大概是 5M 大小，我目前没有尝试重新训练模型，用的现成的
https://github.com/google/emoji-scavenger-hunt

**Comment by ynulihao** [comment]
我看你的pb文件只有55kb，请问5M的模型是在哪里加载的

**Comment by HunterXuan** [comment]
https://github.com/google/emoji-scavenger-hunt/blob/master/dist/model/group1-shard1of1
