### ISSUE TITLE
Facemesh, IOS 体验版成功，但是安卓不可以

### ISSUE THREAD

**Issue by longerking** [HunterXuan/wx-tfjs-demo#46]
你好，，十分感谢作者贡献这样的学习案例。我这里遇到了一些问题，Facemesh 口红案例在IOS体验版成功，但是安卓体验版失败（而安卓打开体验版成功）。请问作者有遇到过这个问题吗？有相关解决思路吗? 感谢你的任何帮助。

安卓真机调试错误：

![middle_img_v2_3283089e-4133-43d2-8021-0ae13179d07g](https://user-images.githubusercontent.com/37200736/143164456-02a0ca75-8417-4e9b-924d-72e57775a21b.png)

模型网络加载是正确的

![middle_img_v2_2ec6d7a4-de5d-47f7-9649-d58262fd818g](https://user-images.githubusercontent.com/37200736/143164517-0ff01aba-43b0-4141-8b34-7cf58fecf74a.png)

![middle_img_v2_5c9df607-5774-42c6-ac9f-7a42a6fa351g](https://user-images.githubusercontent.com/37200736/143164526-5a27d538-b764-4454-84c4-a9156de8853c.png)

**Comment by HunterXuan** [comment]
直接预览，不要使用真机调试
