### ISSUE TITLE
模型的加载问题

### ISSUE THREAD

**Issue by wulixu** [HunterXuan/wx-tfjs-demo#47]
今天clone下代码，发现模型不能加载。
好像域名也没有备案，可能被block了。
https://www.gstaticcnapps.cn/tfhub-tfjs-modules/google/imagenet/mobilenet_v1_025_224/classification/1/model.json

我想问下，所有对应的模型，能不能再代码里面也存一份，方便自行部署文件服务器.

**Comment by HunterXuan** [comment]
可以手动下载一份，自动部署

**Comment by longerking** [comment]
> 可以手动下载一份，自动部署

你好，我从tensorflow hub下载了一份json和bin，保存到自己的oss上同一个目录下，设置了白名单，但是发现model.json可以请求到，而.bin的缺不可以下载到或者下载为0kb。请问作者的模型地址后端是怎么解决的？

相关错误描述类似可以看这里： https://developers.weixin.qq.com/community/develop/doc/000ce68f188ce0001b2d5ad095bc00

**Comment by longerking** [comment]
@HunterXuan
