### ISSUE TITLE
可不可以把模型放在微信小程序的云数据库上

### ISSUE THREAD

**Issue by Inchel214** [HunterXuan/wx-tfjs-demo#5]
小白琢磨了你的demo很久，发现那个加载模型的API是参数是URL，而且模型55k把它可视化了一下发现挺那个啥的，就是不知道有没有可能把模型放在微信的免费云数据库上来调用模型

**Comment by HunterXuan** [comment]
1. tfjs 的 API 是要走 URL 的，没法放到云数据库上调用
2. 模型不止 55K，那个只是 model.json 里面包含了模型的路径等信息，真正的模型二进制文件大概有 3M。

**Comment by Inchel214** [comment]
1、加载文件那里有两个，一个是weights_manifest.json.，还有一个是tensorflowjs_model.pb，我用浏览器下载下来分别是9.26k和54.4k，我是直接把URL放在浏览器下载的两个文件。
2、还想请教一下那个tf-converter.js里面那段代码在tfjs-converter的哪个文件拿下来的，因为API更新了，好像loadFrozenModel现在不用了。

**Comment by HunterXuan** [comment]
1. 如果没记错，weights_manifest.json 里面有指明一个模型二进制文件的路径，如果你在微信开发者工具里面看网络请求，应该会看到一个 3M 大小的请求
2. 确实是 API 有更新了，loadFrozenModel 已经废弃，新的 API 要求将 weights_manifest 和 tensorflowjs_model.pb 合并成一个 model.json 文件
3. 我最近有代码调整，等小程序发布新版本后，我更新一波 GitHub 上的代码

**Comment by Inchel214** [comment]
1、对的，我刚刚查看了一下json文件和微信开发者工具，里面全部有个path，起初还以为是pb文件里面的一个参数路径，按照路径去下载也的确是3m
2、我查阅tfjs-converter的文档的时候，好像说input_format是model file，这个model file是权重的文件还是整个模型的文件呢，我两个都试过转化好像都ok的样子。
3、期待作者update，如果有需要训练下一个版本模型的话，我这里可以代劳，主要想向作者学习一下

**Comment by HunterXuan** [comment]
新版本正在提交审核，小程序上线后将更新仓库代码。
欢迎大家一起加功能 & 改 BUG
