### ISSUE TITLE
TypeError: this.fetchFunc is not a function

### ISSUE THREAD

**Issue by Cocktail98** [HunterXuan/wx-tfjs-demo#6]
请问您是否遇到过Uncaught (in promise) TypeError: this.fetchFunc is not a function的情况，又是怎样解决的呢？

**Comment by HunterXuan** [comment]
这个问题应该是在早期解决 tfjs 不兼容小程序时才遇到，如果是目前仓库的最新代码，不会有这个问题

**Comment by Cocktail98** [comment]
emmmmm，那么请问您的tfjs版本和插件版本，以及regenerator-runtime和fetch-wechat的版本，非常感谢

**Comment by Cocktail98** [comment]
我使用的tfjs插件为0.0.5，tfjs@1.2.7, fetch-wechat@0.0.3, regenerator-runtime@0.13.3, posenet@2.1.3

**Comment by HunterXuan** [comment]
1. 目前本仓库的最新代码没有用到 tfjs 插件 以及你列出的这几项
2. 目前我发布的最新版的小程序用到的依赖：
```
"@tensorflow/tfjs-core": "^1.2.6",
"@tensorflow/tfjs-converter": "^1.2.6",
"@tensorflow-models/posenet": "^2.1.3",
"fetch-wechat": "0.0.3",
```

**Comment by Cocktail98** [comment]
我用的也是这个几个，只不过没有写全名称
但是我的版本是
"@tensorflow/tfjs-core": "^1.2.7",
"@tensorflow/tfjs-converter": "^1.2.7",
"@tensorflow-models/posenet": "^2.1.3",
"fetch-wechat": "0.0.3",

**Comment by Cocktail98** [comment]
请问您有安装regenerator-runtime么

**Comment by HunterXuan** [comment]
没有装

**Comment by Cocktail98** [comment]
那么您有对依赖做一些处理么，据我所知，我已经遇到了很多跟我有相同问题的人，无法解决这个问题

**Comment by Cocktail98** [comment]
谢谢您的耐心回复，问题已经解决，将tfjs的版本从1.2.7降至1.2.6，既不会出现这个问题，不知道为什么会出现这个bug
