### ISSUE TITLE
wechat-webgl初始化失败

### ISSUE THREAD

**Issue by Inchel214** [HunterXuan/wx-tfjs-demo#8]
能运行程序，但是用不了WebGL加速

VM1623:1 Initialization of backend wechat-webgl failed
console.warn @ VM1623:1
t.initializeBackend @ index.js:17
(anonymous) @ index.js:17
(anonymous) @ index.js:17
(anonymous) @ index.js:17
(anonymous) @ index.js:17
r @ index.js:17
t.setBackend @ index.js:17
t.setBackend @ index.js:17
t @ VM1680 appservice.js:1089
exports.setupWechatPlatform @ VM1680 appservice.js:1089
exports.configPlugin @ VM1680 appservice.js:1074
onLaunch @ app.js? [sm]:8
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
pe @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ app.js? [sm]:6
require @ WAService.js:1
(anonymous) @ VM1845:1
scriptLoaded @ appservice?t=1566032884110:7176
script.onload @ appservice?t=1566032884110:7219
load (async)
loadBabelModule @ appservice?t=1566032884110:7213
window.loadBabelMod @ appservice?t=1566032884110:7227
(anonymous) @ slicedToArray.js:12
VM1623:1 Error: Cannot get WebGL rendering context, WebGL is disabled

**Comment by HunterXuan** [comment]
什么机型？

**Comment by Inchel214** [comment]
模拟器里面iPhone全系列都初始化失败，另外Nexus应该是安卓系统的吧，用Nexus6编译也是初始化失败。

**Comment by HunterXuan** [comment]
应该是模拟器不能使用 wx.createOffscreenCanvas() 这个 API，尽量在真机上测试

**Comment by Inchel214** [comment]
官方文档说wx.creteOffscreenCanvas()这个API不支持真机调试，模拟器应该是可以就是准确的，我看了代码猜测有没有可能是因为没调用offscreencanvas的实例，而直接调用camera的实例导致初始化失败的呢

**Comment by HunterXuan** [comment]
我指的真机是指直接扫码运行小程序测试，我这边的 IDE 提示我「IDE 暂不支持 camera 组件，请在真机测试」，所以我都是用预览功能，然后打日志的方式测试。

**Comment by Inchel214** [comment]
好的，thx
