### ISSUE TITLE
部署小程序

### ISSUE THREAD

**Issue by ThatNight** [HunterXuan/wx-tfjs-demo#9]
![image](https://user-images.githubusercontent.com/49028624/64905712-f1567580-d70e-11e9-9c87-cbdd284fa74a.png)
请问一下这个怎么解决呢？

**Comment by HunterXuan** [comment]
1. 改过 app.js 吗
2. 执行 npm install 了吗？
3. 使用微信开发者工具的 npm 构建 功能了吗？

**Comment by puyuelin** [comment]
![66ed919efcf5ec138ee08dedd297e69](https://user-images.githubusercontent.com/55343033/64918784-9176d200-d7d5-11e9-9c14-fa2ca02238c6.png)
请问一下这个怎么解决呢？

**Comment by puyuelin** [comment]
![8a48039283ef2cdb340bc194720bc22](https://user-images.githubusercontent.com/55343033/64918830-309bc980-d7d6-11e9-9094-88e404d35271.png)
请问一下这个怎么解决呢？

**Comment by HunterXuan** [comment]
先看一下官方文档吧：https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html

**Comment by puyuelin** [comment]
![ceee54d243206e060434e1dba8e4728](https://user-images.githubusercontent.com/55343033/65864746-01c04e80-e3a5-11e9-8f9b-a17e50704197.png)
您好，请问一下我配置了小程序合法域名之后，它报了这个错误，这是模型域名不正确吗？
